# Generated by Django 5.1.7 on 2025-03-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phon',
            new_name='phonenumber',
        ),
    ]
