# Generated by Django 5.1.7 on 2025-04-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='profiles/Default_pfp.jpg', upload_to='profiles'),
        ),
    ]
