# Generated by Django 5.1.7 on 2025-04-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='ln',
        ),
    ]
