# Generated by Django 5.1.7 on 2025-05-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_location_lat_remove_location_ln'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_choose',
            field=models.BooleanField(default=False),
        ),
    ]
