# Generated by Django 5.1.7 on 2025-05-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_otp_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='location',
            name='reciver',
        ),
        migrations.AddField(
            model_name='location',
            name='home_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='home_plaque',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='home_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
