# Generated by Django 5.1.7 on 2025-03-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rate',
            field=models.FloatField(default=0),
        ),
    ]
