# Generated by Django 5.1.7 on 2025-04-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='stock_2',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_6',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_8',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
