# Generated by Django 5.1.7 on 2025-04-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_stock_product_stock_2_product_stock_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_1',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
