# Generated by Django 5.1.7 on 2025-04-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_stock_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_1',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_8',
        ),
        migrations.AddField(
            model_name='product',
            name='box_color',
            field=models.TextField(default='red'),
        ),
        migrations.AddField(
            model_name='product',
            name='box_type',
            field=models.PositiveIntegerField(choices=[(1, 'Box of 1'), (2, 'Box of 2'), (4, 'Box of 4'), (6, 'Box of 6'), (8, 'Box of 8')], default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
