# Generated by Django 5.1.7 on 2025-05-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rate',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterOrderWithRespectTo(
            name='productcomment',
            order_with_respect_to=None,
        ),
    ]
