# Generated by Django 5.1.7 on 2025-06-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='box_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
