-- Migration: 0001_initial --
BEGIN;
--
-- Create model CartItem
--
CREATE TABLE "cart_cartitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "quantity" integer NOT NULL CHECK ("quantity" >= 0), "product_id" bigint NOT NULL, "user_id" bigint NOT NULL);
ALTER TABLE "cart_cartitem" ADD CONSTRAINT "cart_cartitem_user_id_product_id_e43e4ea0_uniq" UNIQUE ("user_id", "product_id");
ALTER TABLE "cart_cartitem" ADD CONSTRAINT "cart_cartitem_product_id_b24e265a_fk_product_product_id" FOREIGN KEY ("product_id") REFERENCES "product_product" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cart_cartitem" ADD CONSTRAINT "cart_cartitem_user_id_292943b8_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cart_cartitem_product_id_b24e265a" ON "cart_cartitem" ("product_id");
CREATE INDEX "cart_cartitem_user_id_292943b8" ON "cart_cartitem" ("user_id");
COMMIT;


-- Migration: 0002_cartitem_price --
BEGIN;
--
-- Add field price to cartitem
--
ALTER TABLE "cart_cartitem" ADD COLUMN "price" numeric(10, 2) DEFAULT 0 NOT NULL;
ALTER TABLE "cart_cartitem" ALTER COLUMN "price" DROP DEFAULT;
COMMIT;


-- Migration: 0003_remove_cartitem_price --
BEGIN;
--
-- Remove field price from cartitem
--
ALTER TABLE "cart_cartitem" DROP COLUMN "price" CASCADE;
COMMIT;


-- Migration: 0004_alter_cartitem_unique_together_cartitem_box_type_and_more --
BEGIN;
--
-- Alter unique_together for cartitem (0 constraint(s))
--
ALTER TABLE "cart_cartitem" DROP CONSTRAINT "cart_cartitem_user_id_product_id_e43e4ea0_uniq";
--
-- Add field box_type to cartitem
--
ALTER TABLE "cart_cartitem" ADD COLUMN "box_type" integer DEFAULT 2 NOT NULL CHECK ("box_type" >= 0);
ALTER TABLE "cart_cartitem" ALTER COLUMN "box_type" DROP DEFAULT;
--
-- Alter unique_together for cartitem (1 constraint(s))
--
ALTER TABLE "cart_cartitem" ADD CONSTRAINT "cart_cartitem_user_id_product_id_box_type_e5625b9a_uniq" UNIQUE ("user_id", "product_id", "box_type");
COMMIT;


-- Migration: 0005_alter_cartitem_box_type --
BEGIN;
--
-- Alter field box_type on cartitem
--
-- (no-op)
COMMIT;


-- Migration: 0006_alter_cartitem_unique_together_and_more --


-- Migration: 0007_deliverycart --
BEGIN;
--
-- Create model DeliveryCart
--
CREATE TABLE "cart_deliverycart" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "delivery_id" bigint NOT NULL, "user_id" bigint NOT NULL);
ALTER TABLE "cart_deliverycart" ADD CONSTRAINT "cart_deliverycart_delivery_id_d6efea44_fk_order_del" FOREIGN KEY ("delivery_id") REFERENCES "order_deliveryslots" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cart_deliverycart" ADD CONSTRAINT "cart_deliverycart_user_id_343b7cf0_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cart_deliverycart_delivery_id_d6efea44" ON "cart_deliverycart" ("delivery_id");
CREATE INDEX "cart_deliverycart_user_id_343b7cf0" ON "cart_deliverycart" ("user_id");
COMMIT;


