-- Migration: 0001_initial --
BEGIN;
--
-- Create model DiscountCart
--
CREATE TABLE "order_discountcart" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "text" varchar(255) NOT NULL UNIQUE, "percentage" integer NOT NULL CHECK ("percentage" >= 0), "max_discount" numeric(10, 2) NOT NULL, "max_use" integer NOT NULL CHECK ("max_use" >= 0), "first_time" boolean NOT NULL, "expired_time" timestamp with time zone NOT NULL, "payment_without_discount" numeric(10, 2) NOT NULL, "product_id" bigint NULL, "user_id" bigint NOT NULL);
--
-- Create model Order
--
CREATE TABLE "order_order" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "delivery_time" timestamp with time zone NOT NULL, "created_at" timestamp with time zone NOT NULL, "discription" text NOT NULL, "total_price" numeric(10, 2) NOT NULL, "profit" numeric(10, 2) NOT NULL, "status" smallint NOT NULL, "shipping_fee" numeric(10, 2) NOT NULL, "discount_id" bigint NULL, "location_id" bigint NULL, "user_id" bigint NOT NULL);
--
-- Create model OrderItem
--
CREATE TABLE "order_orderitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "quantity" integer NOT NULL CHECK ("quantity" >= 0), "product_discount" integer NOT NULL CHECK ("product_discount" >= 0), "order_id" bigint NOT NULL, "product_id" bigint NOT NULL);
--
-- Create constraint valid_discount_range_cart on model discountcart
--
ALTER TABLE "order_discountcart" ADD CONSTRAINT "valid_discount_range_cart" CHECK (("percentage" >= 0 AND "percentage" <= 100));
ALTER TABLE "order_discountcart" ADD CONSTRAINT "order_discountcart_product_id_f3b58590_fk_product_product_id" FOREIGN KEY ("product_id") REFERENCES "product_product" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "order_discountcart" ADD CONSTRAINT "order_discountcart_user_id_727f1674_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "order_discountcart_text_06e98dac_like" ON "order_discountcart" ("text" varchar_pattern_ops);
CREATE INDEX "order_discountcart_product_id_f3b58590" ON "order_discountcart" ("product_id");
CREATE INDEX "order_discountcart_user_id_727f1674" ON "order_discountcart" ("user_id");
ALTER TABLE "order_order" ADD CONSTRAINT "order_order_discount_id_3234c5db_fk_order_discountcart_id" FOREIGN KEY ("discount_id") REFERENCES "order_discountcart" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "order_order" ADD CONSTRAINT "order_order_location_id_b139a0da_fk_users_location_id" FOREIGN KEY ("location_id") REFERENCES "users_location" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "order_order" ADD CONSTRAINT "order_order_user_id_7cf9bc2b_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "order_order_status_1e381235" ON "order_order" ("status");
CREATE INDEX "order_order_discount_id_3234c5db" ON "order_order" ("discount_id");
CREATE INDEX "order_order_location_id_b139a0da" ON "order_order" ("location_id");
CREATE INDEX "order_order_user_id_7cf9bc2b" ON "order_order" ("user_id");
ALTER TABLE "order_orderitem" ADD CONSTRAINT "order_orderitem_order_id_aba34f44_fk_order_order_id" FOREIGN KEY ("order_id") REFERENCES "order_order" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "order_orderitem" ADD CONSTRAINT "order_orderitem_product_id_c5c6b07a_fk_product_product_id" FOREIGN KEY ("product_id") REFERENCES "product_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "order_orderitem_order_id_aba34f44" ON "order_orderitem" ("order_id");
CREATE INDEX "order_orderitem_product_id_c5c6b07a" ON "order_orderitem" ("product_id");
COMMIT;


-- Migration: 0002_deliveryslots_remove_order_delivery_time_and_more --
BEGIN;
--
-- Create model DeliverySlots
--
CREATE TABLE "order_deliveryslots" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "start_time" time NOT NULL, "end_time" time NOT NULL, "delivery_date" date NOT NULL, "max_orders" integer NOT NULL, "current_fill" integer NOT NULL, "shipping_fee" numeric(10, 2) NOT NULL);
--
-- Remove field delivery_time from order
--
ALTER TABLE "order_order" DROP COLUMN "delivery_time" CASCADE;
--
-- Add field delivey_time to order
--
ALTER TABLE "order_order" ADD COLUMN "delivey_time" timestamp with time zone DEFAULT '2025-05-11T08:32:43.299312+00:00'::timestamptz NOT NULL;
ALTER TABLE "order_order" ALTER COLUMN "delivey_time" DROP DEFAULT;
COMMIT;


-- Migration: 0003_order_delivery --
BEGIN;
--
-- Add field delivery to order
--
ALTER TABLE "order_order" ADD COLUMN "delivery_id" bigint DEFAULT 1 NOT NULL CONSTRAINT "order_order_delivery_id_9cbb9abf_fk_order_deliveryslots_id" REFERENCES "order_deliveryslots"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "order_order_delivery_id_9cbb9abf_fk_order_deliveryslots_id" IMMEDIATE;
ALTER TABLE "order_order" ALTER COLUMN "delivery_id" DROP DEFAULT;
CREATE INDEX "order_order_delivery_id_9cbb9abf" ON "order_order" ("delivery_id");
COMMIT;


-- Migration: 0004_alter_order_delivery --
BEGIN;
--
-- Alter field delivery on order
--
SET CONSTRAINTS "order_order_delivery_id_9cbb9abf_fk_order_deliveryslots_id" IMMEDIATE; ALTER TABLE "order_order" DROP CONSTRAINT "order_order_delivery_id_9cbb9abf_fk_order_deliveryslots_id";
ALTER TABLE "order_order" ADD CONSTRAINT "order_order_delivery_id_9cbb9abf_fk_order_deliveryslots_id" FOREIGN KEY ("delivery_id") REFERENCES "order_deliveryslots" ("id") DEFERRABLE INITIALLY DEFERRED;
COMMIT;


-- Migration: 0005_remove_order_delivey_time_remove_order_shipping_fee --
BEGIN;
--
-- Remove field delivey_time from order
--
ALTER TABLE "order_order" DROP COLUMN "delivey_time" CASCADE;
--
-- Remove field shipping_fee from order
--
ALTER TABLE "order_order" DROP COLUMN "shipping_fee" CASCADE;
COMMIT;


-- Migration: 0006_order_delivered_at --
BEGIN;
--
-- Add field delivered_at to order
--
ALTER TABLE "order_order" ADD COLUMN "delivered_at" timestamp with time zone NULL;
COMMIT;


