-- Migration: 0001_initial --
BEGIN;
--
-- Create model Product
--
CREATE TABLE "product_product" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "category" varchar(255) NOT NULL, "name" varchar(250) NOT NULL, "price" numeric(10, 2) NOT NULL, "description" text NOT NULL, "photo" varchar(100) NOT NULL);
--
-- Create model Discount
--
CREATE TABLE "product_discount" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "percentage" integer NOT NULL CHECK ("percentage" >= 0), "product_id" bigint NOT NULL, CONSTRAINT "valid_discount_range" CHECK (("percentage" >= 0 AND "percentage" <= 100)));
--
-- Create model Rate
--
CREATE TABLE "product_rate" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "rate" double precision NOT NULL, "product_id" bigint NOT NULL, "rated_by_id" bigint NOT NULL, CONSTRAINT "valid_rate_range" CHECK (("rate" >= 1.0 AND "rate" <= 5.0)));
ALTER TABLE "product_discount" ADD CONSTRAINT "product_discount_product_id_7d52e541_fk_product_product_id" FOREIGN KEY ("product_id") REFERENCES "product_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "product_discount_product_id_7d52e541" ON "product_discount" ("product_id");
ALTER TABLE "product_rate" ADD CONSTRAINT "product_rate_product_id_42b3b13a_fk_product_product_id" FOREIGN KEY ("product_id") REFERENCES "product_product" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "product_rate" ADD CONSTRAINT "product_rate_rated_by_id_ccad49f4_fk_users_user_id" FOREIGN KEY ("rated_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "product_rate_product_id_42b3b13a" ON "product_rate" ("product_id");
CREATE INDEX "product_rate_rated_by_id_ccad49f4" ON "product_rate" ("rated_by_id");
COMMIT;


-- Migration: 0002_product_average_rate --
BEGIN;
--
-- Add field average_rate to product
--
ALTER TABLE "product_product" ADD COLUMN "average_rate" double precision DEFAULT 0.0 NOT NULL;
ALTER TABLE "product_product" ALTER COLUMN "average_rate" DROP DEFAULT;
COMMIT;


-- Migration: 0003_remove_discount_product_product_discount_and_more --
BEGIN;
--
-- Remove field product from discount
--
ALTER TABLE "product_discount" DROP COLUMN "product_id" CASCADE;
--
-- Add field discount to product
--
ALTER TABLE "product_product" ADD COLUMN "discount" integer DEFAULT 0 NOT NULL CHECK ("discount" >= 0);
ALTER TABLE "product_product" ALTER COLUMN "discount" DROP DEFAULT;
--
-- Create constraint valid_discount_range on model product
--
ALTER TABLE "product_product" ADD CONSTRAINT "valid_discount_range" CHECK (("discount" >= 0 AND "discount" <= 100));
--
-- Delete model Discount
--
DROP TABLE "product_discount" CASCADE;
COMMIT;


-- Migration: 0004_alter_product_photo --
BEGIN;
--
-- Alter field photo on product
--
-- (no-op)
COMMIT;


-- Migration: 0005_product_stock --
BEGIN;
--
-- Add field stock to product
--
ALTER TABLE "product_product" ADD COLUMN "stock" integer DEFAULT 0 NOT NULL CHECK ("stock" >= 0);
ALTER TABLE "product_product" ALTER COLUMN "stock" DROP DEFAULT;
COMMIT;


-- Migration: 0006_subcategory --
BEGIN;
--
-- Create model SubCategory
--
CREATE TABLE "product_subcategory" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "subcategory" varchar(100) NOT NULL, "product_id" bigint NOT NULL);
ALTER TABLE "product_subcategory" ADD CONSTRAINT "product_subcategory_product_id_f3083e37_fk_product_product_id" FOREIGN KEY ("product_id") REFERENCES "product_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "product_subcategory_product_id_f3083e37" ON "product_subcategory" ("product_id");
COMMIT;


-- Migration: 0007_rename_stock_product_stock_2_product_stock_4_and_more --
BEGIN;
--
-- Rename field stock on product to stock_2
--
ALTER TABLE "product_product" RENAME COLUMN "stock" TO "stock_2";
--
-- Add field stock_4 to product
--
ALTER TABLE "product_product" ADD COLUMN "stock_4" integer DEFAULT 0 NOT NULL CHECK ("stock_4" >= 0);
ALTER TABLE "product_product" ALTER COLUMN "stock_4" DROP DEFAULT;
--
-- Add field stock_6 to product
--
ALTER TABLE "product_product" ADD COLUMN "stock_6" integer DEFAULT 0 NOT NULL CHECK ("stock_6" >= 0);
ALTER TABLE "product_product" ALTER COLUMN "stock_6" DROP DEFAULT;
--
-- Add field stock_8 to product
--
ALTER TABLE "product_product" ADD COLUMN "stock_8" integer DEFAULT 0 NOT NULL CHECK ("stock_8" >= 0);
ALTER TABLE "product_product" ALTER COLUMN "stock_8" DROP DEFAULT;
COMMIT;


-- Migration: 0008_product_stock_1 --
BEGIN;
--
-- Add field stock_1 to product
--
ALTER TABLE "product_product" ADD COLUMN "stock_1" integer DEFAULT 0 NOT NULL CHECK ("stock_1" >= 0);
ALTER TABLE "product_product" ALTER COLUMN "stock_1" DROP DEFAULT;
COMMIT;


-- Migration: 0009_rename_stock_1_product_stock_remove_product_stock_2_and_more --
BEGIN;
--
-- Rename field stock_1 on product to stock
--
ALTER TABLE "product_product" RENAME COLUMN "stock_1" TO "stock";
--
-- Remove field stock_2 from product
--
ALTER TABLE "product_product" DROP COLUMN "stock_2" CASCADE;
--
-- Remove field stock_4 from product
--
ALTER TABLE "product_product" DROP COLUMN "stock_4" CASCADE;
--
-- Remove field stock_6 from product
--
ALTER TABLE "product_product" DROP COLUMN "stock_6" CASCADE;
--
-- Remove field stock_8 from product
--
ALTER TABLE "product_product" DROP COLUMN "stock_8" CASCADE;
--
-- Add field box_color to product
--
ALTER TABLE "product_product" ADD COLUMN "box_color" text DEFAULT 'red' NOT NULL;
ALTER TABLE "product_product" ALTER COLUMN "box_color" DROP DEFAULT;
--
-- Add field box_type to product
--
ALTER TABLE "product_product" ADD COLUMN "box_type" integer DEFAULT 1 NOT NULL CHECK ("box_type" >= 0);
ALTER TABLE "product_product" ALTER COLUMN "box_type" DROP DEFAULT;
--
-- Add field color to product
--
ALTER TABLE "product_product" ADD COLUMN "color" varchar(255) NULL;
COMMIT;


-- Migration: 0010_productcomment --
BEGIN;
--
-- Create model ProductComment
--
CREATE TABLE "product_productcomment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "comment" text NOT NULL, "posted_at" timestamp with time zone NOT NULL, "suggested" integer NOT NULL, "product_id" bigint NOT NULL, "user_id" bigint NOT NULL, "_order" integer NOT NULL);
ALTER TABLE "product_productcomment" ADD CONSTRAINT "product_productcomme_product_id_bf5e6965_fk_product_p" FOREIGN KEY ("product_id") REFERENCES "product_product" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "product_productcomment" ADD CONSTRAINT "product_productcomment_user_id_e1a22ad0_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "product_productcomment_product_id_bf5e6965" ON "product_productcomment" ("product_id");
CREATE INDEX "product_productcomment_user_id_e1a22ad0" ON "product_productcomment" ("user_id");
COMMIT;


