-- Migration: 0001_initial --
BEGIN;
--
-- Create model BreadReservation
--
CREATE TABLE "reserve_breadreservation" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "quantity" integer NOT NULL CHECK ("quantity" >= 0), "period" varchar(10) NOT NULL, "start_date" timestamp with time zone NOT NULL, "active" boolean NOT NULL, "auto_pay" boolean NOT NULL, "location_id" bigint NULL, "product_id" bigint NOT NULL, "user_id" bigint NOT NULL);
ALTER TABLE "reserve_breadreservation" ADD CONSTRAINT "reserve_breadreservation_user_id_product_id_perio_b51a0915_uniq" UNIQUE ("user_id", "product_id", "period");
ALTER TABLE "reserve_breadreservation" ADD CONSTRAINT "reserve_breadreserva_location_id_72bc6069_fk_users_loc" FOREIGN KEY ("location_id") REFERENCES "users_location" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "reserve_breadreservation" ADD CONSTRAINT "reserve_breadreserva_product_id_bfb9f7fe_fk_product_p" FOREIGN KEY ("product_id") REFERENCES "product_product" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "reserve_breadreservation" ADD CONSTRAINT "reserve_breadreservation_user_id_6ba5e413_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "reserve_breadreservation_location_id_72bc6069" ON "reserve_breadreservation" ("location_id");
CREATE INDEX "reserve_breadreservation_product_id_bfb9f7fe" ON "reserve_breadreservation" ("product_id");
CREATE INDEX "reserve_breadreservation_user_id_6ba5e413" ON "reserve_breadreservation" ("user_id");
COMMIT;


-- Migration: 0002_breadreservation_delivery --
BEGIN;
--
-- Add field delivery to breadreservation
--
ALTER TABLE "reserve_breadreservation" ADD COLUMN "delivery_id" bigint NULL CONSTRAINT "reserve_breadreserva_delivery_id_48e425b1_fk_order_del" REFERENCES "order_deliveryslots"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "reserve_breadreserva_delivery_id_48e425b1_fk_order_del" IMMEDIATE;
CREATE INDEX "reserve_breadreservation_delivery_id_48e425b1" ON "reserve_breadreservation" ("delivery_id");
COMMIT;


-- Migration: 0003_remove_breadreservation_start_date --
BEGIN;
--
-- Remove field start_date from breadreservation
--
ALTER TABLE "reserve_breadreservation" DROP COLUMN "start_date" CASCADE;
COMMIT;


