-- Migration: 0001_initial --
BEGIN;
--
-- Create model User
--
CREATE TABLE "users_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "last_login" timestamp with time zone NULL, "username" varchar(100) NOT NULL UNIQUE, "email" varchar(100) NOT NULL UNIQUE, "firstname" varchar(50) NULL, "lastname" varchar(50) NULL, "city" varchar(100) NULL, "phon" varchar(128) NOT NULL UNIQUE, "password" varchar(100) NULL, "is_active" boolean NOT NULL, "is_staff" boolean NOT NULL, "is_superuser" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL);
CREATE TABLE "users_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "users_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
CREATE INDEX "users_user_username_06e46fe6_like" ON "users_user" ("username" varchar_pattern_ops);
CREATE INDEX "users_user_email_243f6e77_like" ON "users_user" ("email" varchar_pattern_ops);
CREATE INDEX "users_user_phon_866e055b_like" ON "users_user" ("phon" varchar_pattern_ops);
ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_user_id_group_id_b88eab82_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_user_id_5f6f5a90_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users_user_groups" ADD CONSTRAINT "users_user_groups_group_id_9afc8d0e_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "users_user_groups_user_id_5f6f5a90" ON "users_user_groups" ("user_id");
CREATE INDEX "users_user_groups_group_id_9afc8d0e" ON "users_user_groups" ("group_id");
ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_permissions_user_id_permission_id_43338c45_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_permissions_user_id_20aca447_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users_user_user_permissions" ADD CONSTRAINT "users_user_user_perm_permission_id_0b93982e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "users_user_user_permissions_user_id_20aca447" ON "users_user_user_permissions" ("user_id");
CREATE INDEX "users_user_user_permissions_permission_id_0b93982e" ON "users_user_user_permissions" ("permission_id");
COMMIT;


-- Migration: 0002_rename_phon_user_phonenumber --
BEGIN;
--
-- Rename field phon on user to phonenumber
--
ALTER TABLE "users_user" RENAME COLUMN "phon" TO "phonenumber";
COMMIT;


-- Migration: 0003_user_otp_user_otp_created_at --
BEGIN;
--
-- Add field otp to user
--
ALTER TABLE "users_user" ADD COLUMN "otp" varchar(6) NULL;
--
-- Add field otp_created_at to user
--
ALTER TABLE "users_user" ADD COLUMN "otp_created_at" timestamp with time zone NULL;
COMMIT;


-- Migration: 0004_otp_remove_user_otp_remove_user_otp_created_at --
BEGIN;
--
-- Create model Otp
--
CREATE TABLE "users_otp" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "phonenumber" varchar(128) NOT NULL UNIQUE, "otp" varchar(6) NULL, "otp_created_at" timestamp with time zone NULL);
--
-- Remove field otp from user
--
ALTER TABLE "users_user" DROP COLUMN "otp" CASCADE;
--
-- Remove field otp_created_at from user
--
ALTER TABLE "users_user" DROP COLUMN "otp_created_at" CASCADE;
CREATE INDEX "users_otp_phonenumber_9f9211fb_like" ON "users_otp" ("phonenumber" varchar_pattern_ops);
COMMIT;


-- Migration: 0005_alter_user_email --
BEGIN;
--
-- Alter field email on user
--
ALTER TABLE "users_user" ALTER COLUMN "email" DROP NOT NULL;
COMMIT;


-- Migration: 0006_alter_otp_otp_created_at_alter_otp_phonenumber --
BEGIN;
--
-- Alter field otp_created_at on otp
--
ALTER TABLE "users_otp" ALTER COLUMN "otp_created_at" SET DEFAULT '2025-05-11T08:33:00.128016+00:00'::timestamptz;
UPDATE "users_otp" SET "otp_created_at" = '2025-05-11T08:33:00.128016+00:00'::timestamptz WHERE "otp_created_at" IS NULL; SET CONSTRAINTS ALL IMMEDIATE;
ALTER TABLE "users_otp" ALTER COLUMN "otp_created_at" SET NOT NULL;
ALTER TABLE "users_otp" ALTER COLUMN "otp_created_at" DROP DEFAULT;
--
-- Alter field phonenumber on otp
--
DROP INDEX IF EXISTS "users_otp_phonenumber_9f9211fb_like";
COMMIT;


-- Migration: 0007_user_profile_photo --
BEGIN;
--
-- Add field profile_photo to user
--
ALTER TABLE "users_user" ADD COLUMN "profile_photo" varchar(100) DEFAULT 'Default_pfp.jpg' NOT NULL;
ALTER TABLE "users_user" ALTER COLUMN "profile_photo" DROP DEFAULT;
COMMIT;


-- Migration: 0008_alter_user_profile_photo --
BEGIN;
--
-- Alter field profile_photo on user
--
-- (no-op)
COMMIT;


-- Migration: 0009_alter_user_profile_photo --
BEGIN;
--
-- Alter field profile_photo on user
--
-- (no-op)
COMMIT;


-- Migration: 0010_alter_user_profile_photo --
BEGIN;
--
-- Alter field profile_photo on user
--
-- (no-op)
COMMIT;


-- Migration: 0011_location --
BEGIN;
--
-- Create model Location
--
CREATE TABLE "users_location" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "lat" double precision NULL, "ln" double precision NULL, "address" text NOT NULL, "name" varchar(255) NOT NULL, "detail" text NULL, "phonenumber" varchar(128) NULL, "reciver" varchar(255) NULL, "user_id" bigint NOT NULL);
ALTER TABLE "users_location" ADD CONSTRAINT "users_location_user_id_3bae858a_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "users_location_user_id_3bae858a" ON "users_location" ("user_id");
COMMIT;


-- Migration: 0012_remove_location_lat_remove_location_ln --
BEGIN;
--
-- Remove field lat from location
--
ALTER TABLE "users_location" DROP COLUMN "lat" CASCADE;
--
-- Remove field ln from location
--
ALTER TABLE "users_location" DROP COLUMN "ln" CASCADE;
COMMIT;


-- Migration: 0013_location_is_choose --
BEGIN;
--
-- Add field is_choose to location
--
ALTER TABLE "users_location" ADD COLUMN "is_choose" boolean DEFAULT false NOT NULL;
ALTER TABLE "users_location" ALTER COLUMN "is_choose" DROP DEFAULT;
COMMIT;


