# Generated by Django 5.1.7 on 2025-05-07 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_delivey_time_remove_order_shipping_fee'),
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadreservation',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.deliveryslots'),
        ),
    ]
