# Generated by Django 5.1.7 on 2025-04-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadreservation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
