# Generated by Django 5.1.7 on 2025-08-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='auto_pay',
        ),
        migrations.AddField(
            model_name='reservation',
            name='pay_status',
            field=models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('pending', 'در حال بررسی'), ('failed', 'ناموفق')], default='unpaid', max_length=20),
        ),
    ]
