# Generated by Django 5.1.7 on 2025-05-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_breadreservation_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadreservation',
            name='start_date',
        ),
    ]
