# Generated by Django 5.1.7 on 2025-05-12 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productcomment'),
        ('reserve', '0003_remove_breadreservation_start_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='breadreservation',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ReserveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserve.breadreservation')),
            ],
        ),
        migrations.RemoveField(
            model_name='breadreservation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='breadreservation',
            name='quantity',
        ),
    ]
