# Generated by Django 5.1.7 on 2025-04-18 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_price'),
        ('product', '0006_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='box_type',
            field=models.PositiveIntegerField(choices=[(2, 'Box of 2'), (4, 'Box of 4'), (6, 'Box of 6'), (8, 'Box of 8')], default=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'product', 'box_type')},
        ),
    ]
