# Generated by Django 5.1.7 on 2025-04-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_unique_together_cartitem_box_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='box_type',
            field=models.PositiveIntegerField(choices=[(1, 'Box of 1'), (2, 'Box of 2'), (4, 'Box of 4'), (6, 'Box of 6'), (8, 'Box of 8')]),
        ),
    ]
