# Generated by Django 5.1.7 on 2025-04-20 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_box_type'),
        ('product', '0009_rename_stock_1_product_stock_remove_product_stock_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'product')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='box_type',
        ),
    ]
