# Generated by Django 5.1.7 on 2025-05-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
    ]
