# Generated by Django 5.1.7 on 2025-05-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_admin_check_ticket_is_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
