# Generated by Django 5.1.7 on 2025-08-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticket_admin_user_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('technical', 'پشتیبانی و فنی'), ('payment', 'مالی و پرداخت'), ('public', 'عمومی'), ('suggestions', 'پیشنهادات')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('normal', 'معمولی'), ('urgent', 'فوری'), ('important', 'مهم')], db_index=True, max_length=20),
        ),
    ]
