# Generated by Django 5.1.7 on 2025-05-07 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('delivery_date', models.DateField()),
                ('max_orders', models.IntegerField()),
                ('current_fill', models.IntegerField()),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='order',
            name='delivey_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
