# Generated by Django 5.1.7 on 2025-04-13 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order'),
        ),
        migrations.CreateModel(
            name='DiscountCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('max_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_use', models.PositiveIntegerField(default=10)),
                ('first_time', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.discountcart'),
        ),
        migrations.AddConstraint(
            model_name='discountcart',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gte', 0), ('percentage__lte', 100)), name='valid_discount_range_cart'),
        ),
    ]
