# Generated by Django 5.1.7 on 2025-05-07 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_deliveryslots_remove_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='order.deliveryslots'),
        ),
    ]
