# Generated by Django 5.1.7 on 2025-04-13 20:37

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcart',
            name='expired_time',
            field=models.DateTimeField(default=order.models.default_expired_time),
        ),
    ]
