# Generated by Django 5.1.7 on 2025-05-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivey_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_fee',
        ),
    ]
