# Generated by Django 5.1.7 on 2025-04-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_discountcart_expired_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcart',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
    ]
