# Generated by Django 5.1.7 on 2025-04-14 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_discountcart_first_time'),
        ('product', '0006_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
