# Generated by Django 5.1.7 on 2025-04-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_discountcart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcart',
            name='text',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
