# Generated by Django 5.1.7 on 2025-05-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('pending', 'در حال بررسی'), ('failed', 'ناموفق')], default='unpaid', max_length=20),
        ),
    ]
