# Generated by Django 5.1.7 on 2025-05-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
