# Generated by Django 5.1.7 on 2025-04-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_discountcart_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
