# Generated by Django 5.1.7 on 2025-05-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_ref_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='pay_status',
        ),
    ]
