# Generated by Django 5.1.7 on 2025-04-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcart',
            name='payment_without_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
