# Generated by Django 5.1.7 on 2025-05-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_rename_payment_status_order_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reciver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reciver_phon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
