# Generated by Django 5.1.7 on 2025-04-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_discountcart_payment_without_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='box_type',
            field=models.PositiveIntegerField(choices=[(2, 'Box of 2'), (4, 'Box of 4'), (6, 'Box of 6'), (8, 'Box of 8')], default=2),
            preserve_default=False,
        ),
    ]
