# Generated by Django 5.1.7 on 2025-05-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_reciver_order_reciver_phon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reciver_phon',
            new_name='reciver_phone',
        ),
    ]
