# Generated by Django 5.1.7 on 2025-04-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='box_type',
        ),
    ]
