# Generated by Django 5.1.7 on 2025-05-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_cancelorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_admin_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CancelOrder',
        ),
    ]
