# Generated by Django 5.1.7 on 2025-06-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_admin_reason_order_is_admin_canceled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
