# Generated by Django 5.1.7 on 2025-06-07 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_is_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discription',
            new_name='description',
        ),
    ]
